version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: viveo-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-viveo_root_password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-viveo_db}
      MYSQL_USER: ${MYSQL_USER:-viveo_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-viveo_password}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - viveo-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: viveo-backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER:-viveo_user}:${MYSQL_PASSWORD:-viveo_password}@mysql:3306/${MYSQL_DATABASE:-viveo_db}
      - SECRET_KEY=${SECRET_KEY:-your-super-secret-key-change-in-production}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - backend_logs:/app/logs
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - viveo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: viveo-frontend
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - viveo-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: viveo-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - viveo-network

volumes:
  mysql_data:
  backend_logs:

networks:
  viveo-network:
    driver: bridge